server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23306/my_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: my_test_user
    password: 123456

logging:
  level:
    com.zlgcloud: DEBUG

